name: location_marker_example
description: Example of FlutterMapLocationMarkerPlugin
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  flutter_joystick: ^0.0.2
  flutter_map: any
  flutter_map_location_marker:
    path: ../
  geolocator: ^8.0.5
  latlong2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:

  uses-material-design: true
