name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 0.0.1+1
author: tlsv6y <tlserver6y@gmail.com>
homepage: https://github.com/tlserver/flutter_map_location_marker

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.4.3
  flutter_map: ^0.10.1+1
  geolocator: ^5.3.2+2
  latlong: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
